/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task;

import java.sql.DriverManager;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yasser
 */
public class Student_Form extends javax.swing.JFrame {

    /**
     * Creates new form Student_Form
     */
    public Student_Form() {
        initComponents();
    }
    
    
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    String url = "jdbc:derby://localhost:1527/javaProject";
    String driver = "org.apache.derby.jdbc.ClientDriver";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtname = new javax.swing.JTextField();
        errors = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        userID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Name", "Email", "Age", "Phone"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        txtname.setName("txtname"); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        errors.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        errors.setForeground(new java.awt.Color(255, 0, 0));

        txtmail.setName("txtmail"); // NOI18N
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmailKeyReleased(evt);
            }
        });

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });

        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Email");

        jLabel3.setText("Age");

        jLabel4.setText("Phone");

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtphone)
                            .addComponent(txtage)
                            .addComponent(txtmail)
                            .addComponent(txtname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(errors, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(91, 91, 91)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errors, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete)
                            .addComponent(update))
                        .addGap(40, 40, 40)
                        .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel)table.getModel();

        String name = txtname.getText();
        String mail = txtmail.getText();
        String age = txtage.getText();
        String phone = txtphone.getText();
        
        
        String Email_Pattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(mail);

        
        if (name.isEmpty() || mail.isEmpty() || age.isEmpty() || phone.isEmpty()) {
            errors.setText("One or more inputs are missing !!");
        }
        else if (matcher.matches() == false) {
            errors.setText("Invalid Email");
        } else {
            errors.setText("");
            try {
                
                Class.forName(driver).newInstance();
                con = DriverManager.getConnection(url,"yasser","123456");
                System.out.println("Connected !!");
                
                String sql="INSERT INTO users(Name, Email, Age, Phone)"
                + "VALUES('"+name+"','"+mail+"','"+age+"','"+phone+"')";
                
                st = con.createStatement();
                st.executeUpdate(sql);
                st.close();
                
                st = con.createStatement();
                rs = st.executeQuery("SELECT * FROM users ORDER BY UserID DESC FETCH FIRST ROW ONLY");

                Object[] row = new Object[5];
                while(rs.next()) {

                    row[0] = rs.getString(1);
                    row[1] = rs.getString(2);
                    row[2] = rs.getString(3);
                    row[3] = rs.getString(4);
                    row[4] = rs.getString(5);
                    model.addRow(row);
                }
                
                
                st.close();
                con.close();
                System.out.println("Disconnected !!");
                
                txtname.setText("");
                txtmail.setText("");
                txtage.setText("");
                txtphone.setText("");
                userID.setText("");
                errors.setText("");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_addActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table.getModel();

        
        try {
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url,"yasser","123456");
            System.out.println("Connected !!");
            
            
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM users ORDER BY UserID ASC");

            Object[] row = new Object[5];
            while(rs.next()) {

                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                model.addRow(row);
            }
            
            
            st.close();
            con.close();
            System.out.println("Disconnected !!");

        } catch (Exception e) {
            System.out.println("Error");
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        String x = table.getModel().getValueAt(table.getSelectedRow(), 0).toString();
        try {
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url,"yasser","123456");
            System.out.println("Connected !!");
            
            String sql="DELETE FROM users WHERE UserID = "+x;
            
            st = con.createStatement();
            st.executeUpdate(sql);
            
            st.close();
            con.close();
            System.out.println("Disconnected !!");
            
            ((DefaultTableModel)table.getModel()).removeRow(table.getSelectedRow());
            
            
            txtname.setText("");
            txtmail.setText("");
            txtage.setText("");
            txtphone.setText("");
            userID.setText("");
            errors.setText("");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        userID.setText(table.getModel().getValueAt(table.getSelectedRow(), 0).toString());
        txtname.setText(table.getModel().getValueAt(table.getSelectedRow(), 1).toString());
        txtmail.setText(table.getModel().getValueAt(table.getSelectedRow(), 2).toString());
        txtage.setText(table.getModel().getValueAt(table.getSelectedRow(), 3).toString());
        txtphone.setText(table.getModel().getValueAt(table.getSelectedRow(), 4).toString());
        
    }//GEN-LAST:event_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

        String name = txtname.getText();
        String mail = txtmail.getText();
        String age = txtage.getText();
        String phone = txtphone.getText();
        
        String Email_Pattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(mail);
        
        
        if (name.isEmpty() || mail.isEmpty() || age.isEmpty() || phone.isEmpty()) {
            errors.setText("One or more inputs are missing !!");
        }
        else if (matcher.matches() == false) {
            errors.setText("Invalid Email");
        } else {

            errors.setText("");

            try {
                
                Class.forName(driver).newInstance();
                con = DriverManager.getConnection(url,"yasser","123456");
                System.out.println("Connected !!");
                
                String sql="update users set Name = '" + name + "', Email = '" +mail+ "', Age = '" +age+
                        "', Phone= '"+phone+"' where UserID = " + userID.getText();
                
                st = con.createStatement();
                st.executeUpdate(sql);
                
                st.close();
                con.close();
                System.out.println("Disconnected !!");
                
                
                table.getModel().setValueAt(txtmail.getText(), table.getSelectedRow(), 2);
                table.getModel().setValueAt(txtname.getText(), table.getSelectedRow(), 1);
                table.getModel().setValueAt(txtage.getText(), table.getSelectedRow(), 3);
                table.getModel().setValueAt(txtphone.getText(), table.getSelectedRow(), 4);
                
                
                txtname.setText("");
                txtmail.setText("");
                txtage.setText("");
                txtphone.setText("");
                userID.setText("");
                errors.setText("");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    
    
    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        
        int key = evt.getKeyCode();
        if(!(key >= evt.VK_0 && key <= evt.VK_9) && !(key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == evt.VK_BACK_SPACE))
        {
            txtname.setEditable(true);
        }
        else
        {
            txtname.setEditable(false);
        }

    }//GEN-LAST:event_txtnameKeyPressed
    
    
    
    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        // TODO add your handling code here:
       
        int key = evt.getKeyCode();
        if((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == evt.VK_BACK_SPACE))
        {
            txtage.setEditable(true);
            
        }
        else
        {
            txtage.setEditable(false);
        }
        
    }//GEN-LAST:event_txtageKeyPressed
    
    
    
    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
        
        
        int key = evt.getKeyCode();
        if((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == evt.VK_BACK_SPACE))
        {
            txtphone.setEditable(true);
        }
        else
        {
            txtphone.setEditable(false);
        }
        
    }//GEN-LAST:event_txtphoneKeyPressed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JLabel errors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JButton update;
    private javax.swing.JLabel userID;
    // End of variables declaration//GEN-END:variables
}
